### PR TITLE
Tolerate None language for work uri

### PR DESCRIPTION
**Pull request by longhotsummer**

### CODE REVIEW

**Review by goose-life — COMMENTED** [review]
The code makes sense to me, but I just want to double check: shouldn't an expression uri always have a language? in which case, shouldn't there be an error when the language is missing rather than returning a uri without the language?

**Comment by longhotsummer** [comment]
Good point. So calling `expression_uri()` or `manifestation_uri()` if there is no language or expression date, would through a ValueError, say?

**Comment by goose-life** [comment]
Sounds good to me!

**Comment by goose-life** [comment]
I've checked out a branch from this and will be making a PR soon

**Comment by goose-life** [comment]
I've re-read https://docs.oasis-open.org/legaldocml/akn-nc/v1.0/os/akn-nc-v1.0-os.html#_Toc531692271 and it seems that the date expression date isn't required after all, and while the description says `@` is required the examples include several without, which means it's the current version. So I'm going to suggest just making the language required for the time being and maybe we can check with the TC about the expression date before making changes there?

**Comment by longhotsummer** [comment]
That makes sense.

I agree the standard isn't clear. In reality I believe that an expression FRBR URI always has a date component, either explicit or implicit. 

The standard says that a dangling "@" means the original version, and a dangling ":" means "any", but which Indigo interprets to be the equivalent of `:<today>` --> the expression at or before today's date.

So, effectively, an expression URI without a date can be interpreted to have either an implicit dangling "@" or ":". Indigo assumes it's the latter.

**Comment by longhotsummer** [comment]
The standard doesn't always differentiate clearly between generating an FRBR URI and parsing/consuming/interpreting an FRBR URI.

**Review by goose-life — APPROVED** [review]

**Pull request merged**
